version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0
  aws-eks: circleci/aws-eks@1.1
  gh-release: escaletech/gh-conventional-release@0.1

jobs:
  install-and-test:
    docker:
      - image: circleci/node:10
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "npm-shrinkwrap.json" }}
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths: [node_modules]

ci_only: &ci_only
  filters:
    tags: { ignore: /.*/ }

staging_only: &staging_only
  filters:
    branches: { only: [master] }
    tags: { ignore: /.*/ }

production_only: &production_only
  filters:
    branches: { ignore: /.*/ }
    tags: { only: /^v.*/ }

workflows:
  version: 2
  ci:
    jobs:
      - install-and-test:
          <<: *ci_only
  staging:
    jobs:
      - install-and-test:
          <<: *staging_only
      - aws-ecr/build-and-push-image:
          context: eks-apps-escale-staging
          repo: tog-management-server
          create-repo: true
          attach-workspace: true
          tag: ${CIRCLE_SHA1:0:7},master
          dockerfile: Dockerfile
          requires: [install-and-test]
          <<: *staging_only

  release:
    jobs:
      - install-and-test:
          <<: *production_only
      - aws-ecr/build-and-push-image:
          context: eks-applications
          repo: tog-management-server
          create-repo: true
          attach-workspace: true
          tag: ${CIRCLE_TAG#v},latest
          dockerfile: Dockerfile
          requires: [install-and-test]
          <<: *production_only
      - gh-release/create-release:
          context: github-create-release
          requires: [aws-ecr/build-and-push-image]
          <<: *production_only
