version: 2.1

orbs:
  gh-release: escaletech/gh-conventional-release@0.1

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "npm-shrinkwrap.json" }}
      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run: ./docker_deploy.sh escaletech/tog-management-server

ci_only: &ci_only
  filters:
    tags: { ignore: /.*/ }

production_only: &production_only
  filters:
    branches: { ignore: /.*/ }
    tags: { only: /^v.*/ }

workflows:
  version: 2
  ci:
    jobs:
      - test:
          <<: *ci_only
  release:
    jobs:
      - deploy:
          <<: *production_only
      - gh-release/create-release:
          context: github-create-release
          requires: [deploy]
          <<: *production_only
